source 'https://github.com/artsy/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

workspace ‘ProsperBorrowerSDKSample’

# https://github.com/AFNetworking/AFNetworking
pod "AFNetworking", "~> 3.1.0"

# https://github.com/AFNetworking/AFOAuth2Manager
pod "AFOAuth2Manager", "~> 3.0.0"

pod 'GoogleMaps', '~> 2.2'
pod 'GooglePlaces', '~> 2.2'
pod 'AdobeMobileSDK', '~> 4.13.2'

target :ProsperBorrowerSDKSample do
xcodeproj 'ProsperBorrowerSDKSample.xcodeproj'
end






