source 'https://github.com/artsy/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

use_frameworks!

workspace ‘ProsperSDKSwiftSample’

# https://github.com/AFNetworking/AFNetworking
pod "AFNetworking", "~> 3.2.0"

# https://github.com/AFNetworking/AFOAuth2Manager
pod "AFOAuth2Manager", "~> 3.0.0"

pod 'AdobeMobileSDK', '~> 4.15.0'

target :ProsperSDKSwiftSample do
xcodeproj 'ProsperSDKSwiftSample.xcodeproj'
end






