source 'https://github.com/artsy/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

#workspace ‘ProsperBorrowerSDK’

# https://github.com/AFNetworking/AFNetworking
 pod "AFNetworking", "~> 2.6.2"

# https://github.com/AFNetworking/AFOAuth2Manager
 pod "AFOAuth2Manager", "~> 2.2.0"

 pod 'GoogleMaps'






